using Microsoft.EntityFrameworkCore;
using System;

namespace InventoryManagementWeb.Models
{
    public partial class InventoryDBContext : DbContext
    {
        public InventoryDBContext(DbContextOptions<InventoryDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder);
            //add connection string here
            optionsBuilder.UseSqlServer("Server=.;Database=InventoryDB;Trusted_Connection=True;TrustServerCertificate=True;");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Transaction>(entity =>
            {
                entity.ToTable("Transactions");

                entity.HasKey(e => e.TransactionId).HasName("PK__Transact__55433A4B63DDBB3A");

                // Remove this line if present to allow SQL Server to manage TransactionID
                // entity.Property(e => e.TransactionId)
                //       .HasColumnName("TransactionID")
                //       .ValueGeneratedNever(); // Avoid using OUTPUT clause

                entity.Property(e => e.Date)
                      .HasDefaultValueSql("(getdate())")
                      .HasColumnType("datetime");

                entity.Property(e => e.ProductId).HasColumnName("ProductID");
                entity.Property(e => e.TransactionType)
                      .HasMaxLength(10)
                      .IsRequired();

                entity.HasOne(d => d.Product)
                      .WithMany(p => p.Transactions)
                      .HasForeignKey(d => d.ProductId)
                      .HasConstraintName("FK__Transacti__Produ__398D8EEE");
            });

            // Additional configurations for other entities (if any)

            OnModelCreatingPartial(modelBuilder);
        }

        // This method was autogenerated by Visual Studio; ensure it's correctly implemented
        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
